// SPDX-FileCopyrightText: 2025 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System;
using System.Text.Json.Serialization;

namespace Nethermind.Test.Runner.CrossVM;

/// <summary>
/// Metadata embedded in corpus entries for cross-VM trace comparison.
/// </summary>
/// <remarks>
/// Following the EEST standard, this metadata is stored in the "_info" field inside each test object (not at the top level).
/// Example (EEST-compliant format):
/// <code>
/// {
///   "testName": {
///     "_info": {
///       "comment": "Cross-VM consensus verification test",
///       "generatedBy": "geth",
///       "traceHash": "abc123def456...",
///       "stateRoot": "0x...",
///       "traceLines": 7,
///       "crossvmVersion": "1.0",
///       "generatedAt": "2025-12-08T12:00:00Z"
///     },
///     "env": { ... },
///     "pre": { ... },
///     "transaction": { ... },
///     "post": { ... }
///   }
/// }
/// </code>
/// </remarks>
[JsonUnmappedMemberHandling(JsonUnmappedMemberHandling.Skip)]
public class CrossVMMetadata
{
    /// <summary>
    /// Current version of the cross-VM metadata specification.
    /// </summary>
    public const string CROSSVM_SPEC_VERSION = "1.0";

    /// <summary>
    /// Gets or sets the client that generated this metadata.
    /// </summary>
    [JsonPropertyName("generatedBy")]
    public string? GeneratedBy { get; set; }

    /// <summary>
    /// Gets or sets the MD5 hash of normalized trace + stateRoot.
    /// </summary>
    [JsonPropertyName("traceHash")]
    public string? TraceHash { get; set; }

    /// <summary>
    /// Gets or sets the post-execution state root.
    /// </summary>
    [JsonPropertyName("stateRoot")]
    public string? StateRoot { get; set; }

    /// <summary>
    /// Gets or sets the version of the cross-VM specification.
    /// </summary>
    [JsonPropertyName("crossvmVersion")]
    public string? CrossvmVersion { get; set; }

    /// <summary>
    /// Gets or sets the human-readable description.
    /// </summary>
    [JsonPropertyName("comment")]
    public string? Comment { get; set; }

    /// <summary>
    /// Gets or sets the number of trace lines.
    /// </summary>
    [JsonPropertyName("traceLines")]
    public int? TraceLines { get; set; }

    /// <summary>
    /// Gets or sets the generation timestamp in ISO 8601 format.
    /// </summary>
    [JsonPropertyName("generatedAt")]
    public string? GeneratedAt { get; set; }

    /// <summary>
    /// Gets or sets the client version string.
    /// </summary>
    [JsonPropertyName("version")]
    public string? Version { get; set; }

    /// <summary>
    /// Gets or sets the fork name.
    /// </summary>
    [JsonPropertyName("fork")]
    public string? Fork { get; set; }

    /// <summary>
    /// Gets or sets the fixture format.
    /// </summary>
    [JsonPropertyName("fixture-format")]
    public string? FixtureFormat { get; set; }

    /// <summary>
    /// Gets or sets the filling RPC server client/version string.
    /// </summary>
    [JsonPropertyName("filling-rpc-server")]
    public string? FillingRpcServer { get; set; }

    /// <summary>
    /// Gets or sets the source file path.
    /// </summary>
    [JsonPropertyName("source")]
    public string? Source { get; set; }

    /// <summary>
    /// Gets or sets the SHA256 hash of the source file.
    /// </summary>
    [JsonPropertyName("sourceHash")]
    public string? SourceHash { get; set; }

    /// <summary>
    /// Checks if this metadata was generated by a different client.
    /// </summary>
    /// <param name="thisClient">The current client name (e.g., "nethermind")</param>
    /// <returns>True if generatedBy is set and differs from thisClient</returns>
    public bool IsFromOtherClient(string thisClient) =>
        GeneratedBy is not null && !GeneratedBy.Equals(thisClient, StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Checks if this metadata has a valid trace hash.
    /// </summary>
    /// <returns>True if traceHash is non-null and non-empty</returns>
    public bool HasTraceHash() => !string.IsNullOrEmpty(TraceHash);

    /// <summary>
    /// Checks if this metadata has all required fields per CROSSVM_INFO_SPEC.md.
    /// </summary>
    /// <returns>True if generatedBy, traceHash, stateRoot, and crossvmVersion are all set</returns>
    public bool HasRequiredFields() =>
        !string.IsNullOrEmpty(GeneratedBy) &&
        !string.IsNullOrEmpty(TraceHash) &&
        !string.IsNullOrEmpty(StateRoot) &&
        !string.IsNullOrEmpty(CrossvmVersion);

    public override string ToString()
    {
        string traceHashShort = TraceHash is not null && TraceHash.Length > 8 ? TraceHash[..8] : TraceHash ?? "null";
        string stateRootShort = StateRoot is not null && StateRoot.Length > 10 ? StateRoot[..10] : StateRoot ?? "null";
        return $"CrossVMMetadata{{generatedBy={GeneratedBy}, version={Version}, traceHash={traceHashShort}, stateRoot={stateRootShort}, lines={TraceLines?.ToString() ?? "null"}, crossvmVersion={CrossvmVersion}}}";
    }
}
