// SPDX-FileCopyrightText: 2025 Demerzel Solutions Limited
// SPDX-License-Identifier: LGPL-3.0-only

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using Autofac;
using Ethereum.Test.Base;
using Ethereum.Test.Base.Interfaces;
using Nethermind.Config;
using Nethermind.Consensus.Processing;
using Nethermind.Consensus.Validators;
using Nethermind.Core;
using Nethermind.Core.Crypto;
using Nethermind.Core.Extensions;
using Nethermind.Core.Specs;
using Nethermind.Core.Test.Modules;
using Nethermind.Crypto;
using Nethermind.Evm;
using Nethermind.Evm.State;
using Nethermind.Evm.TransactionProcessing;
using Nethermind.Int256;
using Nethermind.Logging;
using Nethermind.Specs;
using Nethermind.Specs.Forks;
using Nethermind.Specs.Test;
using Nethermind.Test.Runner.CrossVM;
using Nethermind.Test.Runner.Tracing;

namespace Nethermind.Test.Runner.Validator;

/// <summary>
/// Worker that validates corpus entries against Nethermind's execution.
/// </summary>
public sealed class ValidationWorker
{
    private const string ThisClient = "nethermind";
    private static readonly ILogManager LogManager = LimboLogs.Instance;

    private readonly int _workerId;
    private readonly ChannelReader<string> _jobQueue;
    private readonly ValidationReport _report;
    private readonly string _fork;
    private readonly string? _traceDumpDir;
    private readonly bool _includeFilteredInDump;

    public ValidationWorker(
        int workerId,
        ChannelReader<string> jobQueue,
        ValidationReport report,
        string fork,
        string? traceDumpDir,
        bool includeFilteredInDump)
    {
        _workerId = workerId;
        _jobQueue = jobQueue ?? throw new ArgumentNullException(nameof(jobQueue));
        _report = report ?? throw new ArgumentNullException(nameof(report));
        _fork = fork ?? throw new ArgumentNullException(nameof(fork));
        _traceDumpDir = traceDumpDir;
        _includeFilteredInDump = includeFilteredInDump;
    }

    /// <summary>
    /// Runs the worker loop until the channel is closed or cancellation is requested.
    /// </summary>
    public async Task RunAsync(CancellationToken cancellationToken)
    {
        await foreach (string filePath in _jobQueue.ReadAllAsync(cancellationToken))
        {
            ValidationResult result = await ValidateFileAsync(filePath);
            _report.RecordResult(result);
        }
    }

    private async Task<ValidationResult> ValidateFileAsync(string filePath)
    {
        try
        {
            // Read file contents
            byte[] fileData = await File.ReadAllBytesAsync(filePath);

            // Parse as enhanced corpus entry
            EnhancedCorpusEntry entry = EnhancedCorpusEntry.Parse(fileData);

            // Check if this is a cross-VM entry we should validate
            if (!entry.ShouldVerifyAgainst(ThisClient))
            {
                if (!entry.HasMetadata())
                {
                    return ValidationResult.Skipped(filePath, "no cross-VM metadata");
                }

                CrossVMMetadata? meta = entry.Metadata;
                if (meta is not null && ThisClient.Equals(meta.GeneratedBy, StringComparison.OrdinalIgnoreCase))
                {
                    return ValidationResult.Skipped(filePath, "generated by nethermind");
                }

                return ValidationResult.Skipped(filePath, "no verifiable metadata");
            }

            // Get expected values from metadata
            CrossVMMetadata metadata = entry.Metadata!;
            string? expectedHash = metadata.TraceHash;
            string? expectedStateRoot = metadata.StateRoot;

            if (string.IsNullOrEmpty(expectedHash))
            {
                return ValidationResult.Skipped(filePath, "missing traceHash in metadata");
            }

            // Execute test with tracing
            Stopwatch stopwatch = Stopwatch.StartNew();
            TracingResult? nethermindResult = await ExecuteWithTracingAsync(entry);
            stopwatch.Stop();

            if (nethermindResult is null || string.IsNullOrEmpty(nethermindResult.TraceHash))
            {
                return ValidationResult.Error(filePath, "Execution produced null result");
            }

            // Compare trace hashes
            bool hashMatch = expectedHash.Equals(nethermindResult.TraceHash, StringComparison.OrdinalIgnoreCase);

            if (hashMatch)
            {
                return ValidationResult.Passed(
                    filePath,
                    entry.TestName,
                    metadata.GeneratedBy ?? "unknown",
                    metadata.Version,
                    expectedHash,
                    expectedStateRoot,
                    metadata.TraceLines,
                    nethermindResult.TraceHash,
                    nethermindResult.StateRoot,
                    nethermindResult.TraceLines,
                    stopwatch.Elapsed);
            }
            else
            {
                // Divergence detected
                if (_traceDumpDir is not null)
                {
                    await DumpTraceForDivergenceAsync(entry, filePath);
                }

                return ValidationResult.Diverged(
                    filePath,
                    entry.TestName,
                    metadata.GeneratedBy ?? "unknown",
                    metadata.Version,
                    expectedHash,
                    expectedStateRoot,
                    metadata.TraceLines,
                    nethermindResult.TraceHash,
                    nethermindResult.StateRoot,
                    nethermindResult.TraceLines,
                    stopwatch.Elapsed);
            }
        }
        catch (JsonException e)
        {
            return ValidationResult.Error(filePath, $"Failed to parse JSON: {e.Message}");
        }
        catch (IOException e)
        {
            return ValidationResult.Error(filePath, $"Failed to read file: {e.Message}");
        }
        catch (Exception e)
        {
            return ValidationResult.Error(filePath, $"Execution failed: {e.Message}");
        }
    }

    private async Task<TracingResult?> ExecuteWithTracingAsync(EnhancedCorpusEntry entry)
    {
        return await Task.Run(() =>
        {
            try
            {
                // Parse test JSON without metadata using existing infrastructure
                byte[] testJson = entry.GetTestWithoutMetadata();
                string jsonString = System.Text.Encoding.UTF8.GetString(testJson);

                // Use JsonToEthereumTest to parse the state test
                IEnumerable<EthereumTest> tests = JsonToEthereumTest.ConvertStateTest(jsonString);
                GeneralStateTest? test = tests.FirstOrDefault() as GeneralStateTest;

                if (test is null)
                {
                    return null;
                }

                // Resolve fork spec
                test.Fork = ChainUtils.ResolveSpec(test.Fork, test.ChainId);

                ISpecProvider specProvider = new CustomSpecProvider(
                    test.ChainId,
                    test.ChainId,
                    ((ForkActivation)0, Frontier.Instance),
                    ((ForkActivation)1, test.Fork));

                IConfigProvider configProvider = new ConfigProvider();

                using IContainer container = new ContainerBuilder()
                    .AddModule(new TestNethermindModule(configProvider))
                    .AddSingleton<IBlockhashProvider>(new TestBlockhashProvider())
                    .AddSingleton(specProvider)
                    .AddSingleton(LogManager)
                    .Build();

                IMainProcessingContext mainBlockProcessingContext = container.Resolve<IMainProcessingContext>();
                IWorldState stateProvider = mainBlockProcessingContext.WorldState;
                using IDisposable _ = stateProvider.BeginScope(null);
                ITransactionProcessor transactionProcessor = mainBlockProcessingContext.TransactionProcessor;

                // Initialize test state
                GeneralStateTestBase.InitializeTestState(test.Pre, test.CurrentCoinbase, stateProvider, specProvider);

                // Build block header
                BlockHeader header = new(
                    test.PreviousHash,
                    Keccak.OfAnEmptySequenceRlp,
                    test.CurrentCoinbase,
                    test.CurrentDifficulty,
                    test.CurrentNumber,
                    test.CurrentGasLimit,
                    test.CurrentTimestamp,
                    [])
                {
                    BaseFeePerGas = test.Fork.IsEip1559Enabled ? test.CurrentBaseFee ?? 0xA : UInt256.Zero,
                    StateRoot = test.PostHash,
                    IsPostMerge = test.CurrentRandom is not null,
                    MixHash = test.CurrentRandom,
                    WithdrawalsRoot = test.CurrentWithdrawalsRoot,
                    ParentBeaconBlockRoot = test.CurrentBeaconRoot,
                    ExcessBlobGas = test.CurrentExcessBlobGas ?? (test.Fork is Cancun ? 0ul : null),
                    BlobGasUsed = BlobGasCalculator.CalculateBlobGas(test.Transaction),
                    RequestsHash = test.RequestsHash
                };
                header.Hash = header.CalculateHash();

                IReleaseSpec? spec = specProvider.GetSpec((ForkActivation)test.CurrentNumber);

                if (test.Transaction.ChainId is null)
                    test.Transaction.ChainId = test.ChainId;

                if (test.ParentBlobGasUsed is not null && test.ParentExcessBlobGas is not null)
                {
                    BlockHeader parent = new(
                        parentHash: Keccak.Zero,
                        unclesHash: Keccak.OfAnEmptySequenceRlp,
                        beneficiary: test.CurrentCoinbase,
                        difficulty: test.CurrentDifficulty,
                        number: test.CurrentNumber - 1,
                        gasLimit: test.CurrentGasLimit,
                        timestamp: test.CurrentTimestamp,
                        extraData: [])
                    {
                        BlobGasUsed = (ulong)test.ParentBlobGasUsed,
                        ExcessBlobGas = (ulong)test.ParentExcessBlobGas,
                    };
                    header.ExcessBlobGas = BlobGasCalculator.CalculateExcessBlobGas(parent, spec);
                }

                // Create normalizing tracer
                TraceNormalizer normalizer = new();
                NormalizingTracer tracer = new(normalizer);

                // Validate transaction before execution (matching GeneralStateTestBase behavior)
                // Note: Use Core.ValidationResult to avoid collision with Validator.ValidationResult
                bool txIsValid = new TxValidator(test.ChainId).IsWellFormed(test.Transaction, spec);
                TransactionResult? txResult = null;

                if (txIsValid)
                {
                    // Execute transaction only if valid
                    txResult = transactionProcessor.Execute(
                        test.Transaction,
                        new BlockExecutionContext(header, spec),
                        tracer);
                }

                if (txResult is not null && txResult.Value == TransactionResult.Ok)
                {
                    stateProvider.Commit(specProvider.GetSpec((ForkActivation)1));
                    stateProvider.CommitTree(1);
                    stateProvider.RecalculateStateRoot();
                }
                else
                {
                    stateProvider.Reset();
                }

                // Get tracing result
                string stateRoot = stateProvider.StateRoot?.ToString() ?? "0x0000000000000000000000000000000000000000000000000000000000000000";
                return tracer.GetResult(stateRoot);
            }
            catch
            {
                return null;
            }
        });
    }

    private async Task DumpTraceForDivergenceAsync(EnhancedCorpusEntry entry, string sourcePath)
    {
        try
        {
            string baseName = Path.GetFileNameWithoutExtension(sourcePath);
            string dumpPath = Path.Combine(_traceDumpDir!, $"{baseName}_nethermind.jsonl");

            // For now, we skip detailed trace dumping since it requires additional infrastructure
            // In a full implementation, we would re-execute with a detailed trace writer
            await Task.CompletedTask;
        }
        catch
        {
            // Ignore dump failures
        }
    }
}
